### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'kind')

### ISSUE THREAD

**Issue by silverwind** [webpro-nl/knip#725]
Running against a vite typescript project, I'm hit with this error. Maybe the stack trace will help identify the bug. Also the CJS vite error seems odd, the project is pure ESM.

```
$ npx knip@5.25.2
Analyzing workspace ....
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprec
Analyzing source files...
node_modules/typescript/lib/typescript.js:30130
  return node.kind === 208 /* BindingElement */;
              ^

TypeError: Cannot read properties of undefined (reading 'kind')
    at Object.isBindingElement (node_modules/typescript/lib/typescript.js:30130:15)
    at file://node_modules/knip/dist/typescript/visitors/dynamic-imports/importCall.js:102:32
    at file://node_modules/knip/dist/typescript/visitors/index.js:4:35
    at visit (file://node_modules/knip/dist/typescript/getImportsAndExports.js:223:28)
    at visitNodes (node_modules/typescript/lib/typescript.js:31715:22)
    at forEachChildInArrayLiteralExpression (node_modules/typescript/lib/typescript.js:31861:12)
    at Object.forEachChild (node_modules/typescript/lib/typescript.js:32228:35)
    at visit (file://node_modules/knip/dist/typescript/getImportsAndExports.js:303:12)
    at visitNodes (node_modules/typescript/lib/typescript.js:31715:22)
    at forEachChildInCallOrNewExpression (node_modules/typescript/lib/typescript.js:32182:99)
Thrown at:
    at isBindingElement (node_modules/typescript/lib/typescript.js:30130:15)
    at file://node_modules/knip/dist/typescript/visitors/dynamic-imports/importCall.js:102:32
    at file://node_modules/knip/dist/typescript/visitors/index.js:4:35
    at visit (file://node_modules/knip/dist/typescript/getImportsAndExports.js:223:28)
    at visitNodes (node_modules/typescript/lib/typescript.js:31715:22)
    at forEachChildInArrayLiteralExpression (node_modules/typescript/lib/typescript.js:31861:12)
    at forEachChild (node_modules/typescript/lib/typescript.js:32228:35)
    at visit (file://node_modules/knip/dist/typescript/getImportsAndExports.js:303:12)
    at visitNodes (node_modules/typescript/lib/typescript.js:31715:22)
    at forEachChildInCallOrNewExpression (node_modules/typescript/lib/typescript.js:32182:99)


Node.js v22.4.0

**Comment by webpro** [comment]
> Maybe the stack trace will help identify the bug.

Unfortunately it does not, all I can say not is that most likely the issue is related to an import call (`import('specifier')`).  Please add more details or, even better, a reproduction (https://knip.dev/guides/issue-reproduction).

> Also the CJS vite error seems odd, the project is pure ESM.

Please see https://knip.dev/reference/known-issues#the-cjs-build-of-vites-node-api-is-deprecated

**Comment by silverwind** [comment]
Hmm I guess the only way to find the source will be to continously divide this code base down until only the offending line remains, but I'm not motivated to do that as this is a 50k LOC repo.

If something could be done to indicate the location of the offending code, it'd be appreciated.

**Comment by webpro** [comment]
In this file:

```
node_modules/knip/dist/typescript/visitors/dynamic-imports/importCall.js:102:32
```

Add this line before the one that has `ts.isBindingElement` (line 102):

```
console.log(node.getSourceFile().fileName, specifier)
```

Then run `knip -n`, it should print the file name and the import specifier. That `import()` call is what we're interested in :)

**Comment by webpro** [comment]
You can also try to e.g. `npm i -D https://pkg.pr.new/knip@ae5c341` to see if that fixes your issue, but it does fall back to using the default export, if that specifier can be resolved.

**Comment by dentuzhik** [comment]
Encountered the same issue while tying out knip on our project.

I am getting it on the expression of the following type
```
  const [{foo}] = await Promise.all([
    import('./bar'),
    import('./baz'),
    import('@xyz'),
  ]);
```

It seems that in this case calculating the element based on the index goes wrong, because for on of them element becomes undefined. Hopefully this helps a bit

**Comment by webpro** [comment]
Should be fixed in [v5.27.0](https://github.com/webpro-nl/knip/releases/tag/5.27.0), let me know if it isn't.

**Comment by silverwind** [comment]
Yes, `npx knip@5.27.0` works for me as well now, thanks.

**Comment by fernando-redondo** [comment]
When using Promise.all to import multiple modules and then destructuring the result array with ignored values, the issue persists in version 5.27.0. Here is an example code snippet illustrating the problem:

```
const [ , , thirdImport] = await Promise.all([
    import('pathToFirstImport'),
    import('pathToSecondImport'),
    import('pathToThirdImport'),
]);
```

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.27.1. See [Release 5.27.1](https://github.com/webpro-nl/knip/releases/tag/5.27.1) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
